import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-context";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assembleia de Deus | ADTC 7 de Setembro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`flex flex-col h-screen overflow-hidden ${inter.className}`}>
        <ThemeProvider>
          <Header />
          <main className="flex-1 overflow-auto">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
